# Generated by Django 2.1.5 on 2020-06-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0002_auto_20200612_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile.png', null=True, upload_to=''),
        ),
    ]
