# Generated by Django 2.1.5 on 2020-06-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0007_auto_20200613_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_aBGztjN', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_aBGztjN.png', null=True, upload_to=''),
        ),
    ]
