# Generated by Django 2.1.5 on 2020-06-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0008_auto_20200613_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_aBGztjN.png', null=True, upload_to=''),
        ),
    ]
